### ISSUE TITLE
Error openning file

### ISSUE THREAD

**Issue by Elfe011** [Goz3rr/SatisfactorySaveEditor#270] opened 2023-01-23 02:30 UTC
![Error Satisfactory Save Editor](https://user-images.githubusercontent.com/123342354/213956302-17e3055f-83c6-4929-9c4b-2ce277ae334d.png)
 Hello,
I get this error when I try to open my save file
I tried to open with several versions and I encounter the same error

Can You Help me please ? 

Version of save editor 0.10.2, 0.10.1, 0.9.17

**Comment by bobbymois** [comment] 2023-01-23 03:48
yep program dont work with update 7, there is already a post but nothing happens.

**Comment by Tyrantin** [comment] 2023-02-07 21:28
> ![Error Satisfactory Save Editor](https://user-images.githubusercontent.com/123342354/213956302-17e3055f-83c6-4929-9c4b-2ce277ae334d.png) Hello, I get this error when I try to open my save file I tried to open with several versions and I encounter the same error
> 
> Can You Help me please ?
> 
> Version of save editor 0.10.2, 0.10.1, 0.9.17

Same!

**Comment by ramseyspace** [comment] 2023-02-15 07:50
Same, cant even either!

**Comment by asdfxcvbnnm** [comment] 2023-02-19 23:16
I have been thinking I've done something wrong. but I guess not.

**Comment by budak7273** [comment] 2023-05-28 19:48
Duplicate of #267

**Closed as completed by budak7273** 2023-05-28 19:48 UTC
