### ISSUE TITLE
crash when loading 3.0 save

### ISSUE THREAD

**Issue by Kynelongtail** [Goz3rr/SatisfactorySaveEditor#156] opened 2020-02-16 08:13 UTC
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4209495/log.txt)

**Comment by Kynelongtail** [comment] 2020-02-16 08:15
[3.0.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4209496/3.0.zip)
doesn't like .sav files so zipped it.

**Comment by budak7273** [comment] 2020-02-17 21:24
Thanks for sending in this save. It contains an InterfaceProperty, which we haven't implemented yet as of version 0.9.2. One of the upcoming releases will support this property; I'll comment here again once we've put out an update that can load your save.

**Comment by Kynelongtail** [comment] 2020-02-17 22:45
awesome thanks!

**Comment by philomelus** [comment] 2020-02-18 05:58
I can provide a save as well if desired.

**Comment by budak7273** [comment] 2020-02-18 18:50
@philomelus That would be appreciated. It's always good to have more saves to test with.

**Comment by philomelus** [comment] 2020-02-19 00:06
[Satisfcatory-Saves-20200218.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4222427/Satisfcatory-Saves-20200218.zip)

All of the saves in the archive cause 0.9.2 to crash (they are at different times in the same game).

**Comment by twigletx** [comment] 2020-02-20 10:00
Following :-)

**Comment by GraspGG** [comment] 2020-02-21 15:34
[Experimental_Update3_0.9.2 SaveFile](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4236761/Act_3.zip)

For testing purposes - current Editor does close itself while loading that SaveGame.

**Comment by hardpoorcorn** [comment] 2020-02-21 17:07
Following as well.  Will another sav and log file assist?

**Comment by robfrawley** [comment] 2020-02-21 19:02
Interested in progress as well. I can provide anywhere from 1 to 20 v3 save files if desired.

**Comment by philomelus** [comment] 2020-02-22 01:18
I can offer help if you want it.

I have looked into the issue, and I wonder if a long term kluge would be to instead of the default case throwing an exception for an unknown record type (or handling the exception), just keep the data for the record that is not understood verbatim.  Then when saving, write the record back out as it was when it came in.  There is risk here, as it may need to be modified by changes to other records, but obviously there is no way to know that at that time.

In the above solution, there should still be somewhere that the issue is noted - say at the end of the binary read a single message box notifying the user that "unknown record(s) were found, and they will be left unmodified, which may cause issues when saved in their original state."

**Comment by budak7273** [comment] 2020-02-22 22:38
@Kynelongtail 's, @GraspGG 's, and the two of the saves that @philomelus sent (I didn't test the autosaves) load properly after ef9d53f. Expect a new release soon that supports these saves. Thank you all for your help and sending in saves 👍

**Comment by philomelus** [comment] 2020-02-22 23:53
I can confirm that my current saves are now editable.  Thank you for all the effort!

**Comment by Fatmice** [comment] 2020-02-25 17:04
Crashes with Build 115191.  There is a new build 115661, crashes as well.

**Comment by Tekcruzer** [comment] 2020-02-26 01:47
V 0.9.20 Was working fine yesterday. Then today the app opens but when a load save file is initiated the app closes down.

Following this thread.

**Comment by philomelus** [comment] 2020-02-26 01:50
The version built from current source works;  We are just waiting for an official build post 0.9.2.

**Comment by Tekcruzer** [comment] 2020-02-26 01:53
When will Packaged Release be available (exe)? - Nice job on this by the way!

**Comment by philomelus** [comment] 2020-02-26 02:37
> When will Packaged Release be available (exe)? - Nice job on this by the way!

I have no idea, and I have nothing to do with it other than reporting what I know.  I am in complete agreement, though, fantastic job!

**Comment by Fatmice** [comment] 2020-02-26 17:37
> > When will Packaged Release be available (exe)? - Nice job on this by the way!
> 
> I have no idea, and I have nothing to do with it other than reporting what I know. I am in complete agreement, though, fantastic job!

If this is not the 0.9.2 "release" then what is it?
https://github.com/Goz3rr/SatisfactorySaveEditor/releases/tag/0.9.2
I used the executable from that tag

**Comment by Goz3rr** [comment] 2020-02-26 21:31
I've released 0.9.3 which should resolve the last issues, let me know if you have any further problems

**Closed by Goz3rr** 2020-02-26 21:31 UTC
